=== FEGO2006/JmsStream/MapMessage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by Admin (Altova) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MapMessage">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:choice>
					<xs:element name="node" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType mixed="true">
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="type" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element ref="MapMessage" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FEGO2006/JmsStream/MapMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<MapMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Development\IntelliJ\JmsStream\MapMessage.xsd">
	<node type="String" name="test">test</node>
	<MapMessage name="node1">
		<node type="String" name="test">node</node>
		<node type="String" name="test">test</node>
		<MapMessage name="node1.1">
			<node type="String" name="qqq">shwh</node>
			<node type="String" name="2u37">3323</node>
		</MapMessage>
	</MapMessage>
	<node type="String" name="name">node</node>
	<node type="String" name="bbb">ddd</node>
	<MapMessage name="node2">
		<node type="String" name="xxx">ttt</node>	
	</MapMessage>
</MapMessage>
